#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No color

if [ -f ~/.bash_profile ]; then
  source ~/.bash_profile
fi

# Verify coding standards
if [ ! -f ./vendor/bin/phpcs ]; then
  printf "${RED}phpcs not found. ${YELLOW}Did you run composer install?${NC}\n"
  exit 1
fi

printf "${YELLOW}Checking coding standards...${NC} "

./vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 ./src/ ./tests/

if [ $? != 0 ]; then
  printf "${RED}Please fix the errors before committing.${NC}\n"
  exit 1
else
  printf "${GREEN}OK${NC}\n"
fi

# Check for mess detector
if [ ! -f ./vendor/bin/phpmd ]; then
  printf "${RED}phpmd not found. ${YELLOW}Did you run composer install?${NC}\n"
  exit 1
fi

printf "${YELLOW}Running mess detector...${NC} "

./vendor/bin/phpmd src/ xml cleancode,codesize,controversial,design,naming,unusedcode --reportfile phpmd-report.xml

if [ $? != 0 ]; then
  printf "${RED}Please fix the errors before committing.${NC}\n"
  exit 1
else
  printf "${GREEN}OK${NC}\n"
fi

# Run unit tests
if [ ! -f ./vendor/bin/phpunit ]; then
  printf "${RED}phpunit not found. ${YELLOW}Did you run composer install?${NC}\n"
  exit 1
fi

printf "${YELLOW}Running tests...${NC} "

./vendor/bin/phpunit

if [ $? != 0 ]; then
  printf "${RED}Please make sure the tests pass before committing.${NC}\n"
  exit 1
fi

exit 0;
